import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import ParentBanner from '@/components/widgets/parentBanner'
import Confidence from '@/components/widgets/confidence'
import {React, createContext} from 'react'


import { createClient } from '@supabase/supabase-js'
import History from '@/components/widgets/history'
import Welcome from '@/components/widgets/welcome'
import Suggestions from '@/components/widgets/suggestions'

const supabaseUrl = process.env.SUPABASE_URL
const supabaseKey = process.env.SUPABASE_KEY
const supabase = createClient(supabaseUrl, supabaseKey)



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const data = {
    labels: ['','','','','', '', '', '', '', ''],
    datasets: [{
      data: [12, 19, 13, 15, 15, 13, 14, 18, 18, 15, 9],
      borderColor: ['#01B075'],
      borderWidth: 2,
      grid:{display:false},
      
    }],
  }


  const stats = [
    {name:"velocity", increase:true, score:85},
    {name:"velocity", increase:true, score:85},
    {name:"velocity", increase:false, score:85},
  ]


  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='h-max p-brand'>
        
        <Welcome></Welcome>
        <div className="grid grid-cols-3 grid-rows-3 my-brandgap">
          <div className='col-span-2'>
            <p>Hello</p>
          </div>

        </div>
      </div>
    </>
  )
}
